import { NewPublication } from "@/models/Publication";

export const publications: NewPublication[] = [
  {
    id: '1',
    slug: 'green-patents',
    date: '2024',
    languages: {
      es: {
        title: 'Patentes verdes en México',
        description: 'Análisis de las patentes verdes en México',
        image: '/caiinno-publications/1/portada-es.png',
        downloadLink: '/caiinno-publications/1/Patentes-verdes-final-CAIINNO.pdf',
        tags: ['Patentes', 'Sustentabilidad', 'Innovación']
      },
      en: {
        title: 'Green patents in Mexico',
        description: 'Analysis of green patents in Mexico',
        image: '/caiinno-publications/1/portada-en.png',
        downloadLink: '/caiinno-publications/1/fi-Green-Patents-and-Gender-Identification-in-Mexi_241028_162912.pdf',
        tags: ['Patents', 'Sustainability', 'Innovation']
      }
    }
  },
  {
    id: '2',
    slug: 'mujeres-inventoras-latam',
    date: '2024',
    languages: {
      es: {
        title: 'Mujeres inventoras América Latina',
        description: 'Estudio sobre mujeres inventoras en América Latina',
        image: '/caiinno-publications/2/portada-es.png',
        downloadLink: '/caiinno-publications/2/Mujeres-CAIINNO-GLIPA.pdf',
        tags: ['Mujeres Inventoras', 'América Latina', 'Innovación']
      },
      en: {
        title: 'Women inventors latin america',
        description: 'Study on women inventors in Latin America',
        image: '/caiinno-publications/2/portada-en.png',
        downloadLink: '/caiinno-publications/2/INGLES-CAIINNO-GLIPA.pdf',
        tags: ['Women Inventors', 'Latin America', 'Innovation']
      }
    }
  },
  {
    id: '3',
    slug: 'automatizacion-empleos-covid',
    date: '2024',
    languages: {
      es: {
        title: 'Probabilidad y efecto del COVID-19 en la automatización de empleos en la economía creativa de México',
        description: 'Análisis del impacto del COVID-19 en la automatización de empleos del sector creativo',
        image: '/caiinno-publications/3/portada-es.png',
        downloadLink: '/caiinno-publications/3/Automatizacion-COVID-y-Economia-creativa-Final-.pdf',
        tags: ['COVID-19', 'Automatización', 'Economía Creativa']
      },
      en: {
        title: 'Probability and effect of COVID-19 on job automation in Mexico’s creative ecomony',
        description: 'Analysis of the impact of COVID-19 on job automation in the creative sector',
        image: '/caiinno-publications/3/portada-en.png',
        downloadLink: '/caiinno-publications/3/PROBABILITY-OF-JOB-AUTOMATION-IN-THE-MEXICAN-CREATIVE-ECONOMY.pdf',
        tags: ['COVID-19', 'Automation', 'Creative Economy']
      }
    }
  },
  {
    id: '4',
    slug: 'economia-creativa-mexico',
    date: '2024',
    languages: {
      es: {
        title: 'Economía creativa: México y su impacto en la economía nacional',
        description: 'Análisis del impacto de la economía creativa en México',
        image: '/caiinno-publications/4/portada-es.png',
        downloadLink: '/caiinno-publications/4/Economia-Creativa.pdf',
        tags: ['Economía Creativa', 'México', 'Impacto Económico']
      },
      en: {
        title: 'Creative economy: Mexico and its impact on the national economy',
        description: 'Analysis of the impact of the creative economy in Mexico',
        image: '/caiinno-publications/4/portada-en.png',
        downloadLink: '/caiinno-publications/4/Creative-Economy-final.pdf',
        tags: ['Creative Economy', 'Mexico', 'Economic Impact']
      }
    }
  },
  {
    id: '5',
    slug: 'economia-creativa',
    date: '2024',
    languages: {
      es: {
        title: 'Economía del conocimiento y economía creativa como herramientas para salir de la crisis generada por el COVID-19 en América Latina y el Caribe: un enfoque hacía la Alianza del Pacífico',
        description: 'Estudio sobre la economía creativa',
        image: '/caiinno-publications/5/portada-es.png',
        downloadLink: '/caiinno-publications/5/Economia-Creativa.pdf',
        tags: ['Economía Creativa', 'Innovación'],
        youtubeId: '0M7YtW3MTjs'
      },
      en: {
        title: 'Knowledge economy and creative economy as tools to overcome the crisis generated by COVID-19 in Latin America and the Caribbean: a focus on the Pacific Alliance',
        description: 'Study on the creative economy',
        image: '/caiinno-publications/5/portada-en.png',
        downloadLink: '/caiinno-publications/5/Knowledge-economy-and-creative-economy-CAIINNO-BID.pdf',
        tags: ['Creative Economy', 'Innovation']
      }
    }
  },
  {
    id: '7',
    slug: 'mujeres-inventoras',
    date: '2024',
    languages: {
      es: {
        title: 'Mujeres Inventoras: Patentando en México',
        description: 'Investigación sobre mujeres inventoras y patentes en México, incluyendo análisis de los períodos 2014-2016 y 2017-2020.',
        image: '/caiinno-publications/7/portada-es.png',
        downloadLink: '/caiinno-publications/7/Mujeres-Inventoras-2017-2020_CAIINNO.pdf',
        tags: ['Mujeres Inventoras', 'Patentes', 'Investigación', 'PatentesRosas'],
        youtubeId: 'ocekswReZIA'
      },
      en: {
        title: 'Women Inventors: Patenting in Mexico',
        description: 'Research on women inventors and patents in Mexico, including analysis for the periods 2014–2016 and 2017–2020.',
        image: '/caiinno-publications/7/portada-en.png',
        downloadLink: '/caiinno-publications/7/Mexican-women-inventors-CAIINNO.pdf',
        tags: ['Women Inventors', 'Patents', 'Research', 'PinkPatents']
      }
    }
  },
  {
    id: '13',
    slug: 'propiedad-intelectual-creatividad',
    date: '2017',
    languages: {
      es: {
        title: 'Propiedad Intelectual, Creatividad e Innovación para el Desarrollo de México',
        description: '',
        image: '/caiinno-publications/13/portada-es.png',
        downloadLink: '/caiinno-publications/13/PI-Algunas-Propuestas-CAIINNO.pdf',
        tags: ['Propiedad Intelectual', 'Creatividad', 'Innovación']
      }
    }
  },
  {
    id: '16',
    slug: 'formacion-ciudadana-para-emprendedores',
    date: '2018',
    languages: {
      es: {
        title: 'Formación ciudadana para emprendedores',
        description: '',
        image: '/caiinno-publications/16/portada-es.png',
        downloadLink: '/caiinno-publications/16/formacion-civica1.pdf',
        tags: ['Formación Ciudadana', 'Emprendedores'],
        youtubeId: 'lS12Y_OW3nE',
        otherLinks : [
          { label: 'FOMACIÓN CÍVICA Y ÉTICA EN MÉXICO', url: '/caiinno-publications/16/formacion-civica1.pdf' },
          { label: 'Resumen Ejecutivo "FORMACIÓN CÍVICA Y ÉTICA PARA EMPRENDEDORES"', url: '/caiinno-publications/16/Resumen-ejecutivo.pdf' },
          { label: 'EMPRENDIMIENTO Y GÉNERO EN MÉXICO', url: '/caiinno-publications/16/emprendimiento-y-g%C3%A9nero.pdf' },
          { label: 'VALORES EN LOS NEGOCIOS Y EMPRENDIMIENTO', url: '/caiinno-publications/16/valores-en-los-negocios.pdf' },
          { label: 'EMPRENDIMIENTO Y GÉNERO', url: '/caiinno-publications/16/emprendimiento-y-genero.pdf' },
          { label: 'EVALUACIÓN PARTICIPATIVA', url: '/caiinno-publications/16/EVALUACO%C3%ACN-1.pdf' },
          { label: 'METODOLOGÍA DEL TALLER DE "FORMACIÓN CÍVICA Y ÉTICA PARA EMPRENDEDORES"', url: '/caiinno-publications/16/Metodolog%C3%ADa-del-proyecto-Taller-Emprendimiento-con-Valores.pdf' },
          { label: 'IMPLEMENTACIÓN DEL TALLER DE "FORMACIÓN CÍVICA Y ÉTICA PARA EMPRENDEDORES"', url: '/caiinno-publications/16/Implementaci%C3%B3n-Taller-Emprendimiento-con-Valores.pdf' }
        ]
      },
    }
  },
  {
    id: '18',
    slug: 'habilidades-para-la-innovacion',
    date: '2016',
    languages: {
      es: {
        title: 'Habilidades para la Innovación',
        description: '',
        image: '/caiinno-publications/18/portada-es.png',
        downloadLink: '/caiinno-publications/18/resumen_ejecutivo_habilidades_para_la_innovacion.pdf',
        tags: ['Habilidades', 'Innovación']
      },
    }
  },
  {
    id: '19',
    slug: 'indice-nacional-de-ciencia-tecnologia-e-innvacion',
    date: '2025',
    languages: {
      es: {
        title: 'Índice nacional de ciencia, tecnología e innovación 2025',
        description: '',
        image: '/caiinno-publications/19/portada-es.png',
        downloadLink: '/caiinno-publications/19/CAIINNO-INDICE-2025.pdf',
        tags: ['Habilidades', 'Innovación']
      }
    }
  },
  {
    id: '20',
    slug: 'indice-nacional-de-ciencia-tecnologia-e-innovacion-2018',
    date: '2018',
    languages: {
      es: {
        title: 'Índice nacional de ciencia, tecnología e innovación 2018',
        description: '',
        image: '/caiinno-publications/20/portada-es.png',
        downloadLink: '/caiinno-publications/20/INDICE-2018.pdf',
        tags: ['Habilidades', 'Innovación'],
        youtubeId: '2pqrob4I6iU'
      },
      en: {
        title: 'National Index of Science, Technology and Innovation 2018',
        description: '',
        image: '/caiinno-publications/20/portada-en.png',
        downloadLink: '/caiinno-publications/20/1.2ENINDICE-CTI-2018-2018-briefing.pdf',
        tags: ['Skills', 'Innovation']
      }
    }
  },
  {
    id: '21',
    slug: 'indice-nacional-de-ciencia-tecnologia-e-innovacion-2015',
    date: '2015',
    languages: {
      es: {
        title: 'Índice nacional de ciencia, tecnología e innovación 2015',
        description: '',
        image: '/caiinno-publications/21/portada-es.png',
        downloadLink: '/caiinno-publications/21/INCTI-CAIINNO2015.pdf',
        tags: ['Habilidades', 'Innovación']
      },
      en: {
        title: 'National index of science, technology and innovation 2015',
        description: '',
        image: '/caiinno-publications/21/portada-en.png',
        downloadLink: '/caiinno-publications/21/EN-Briefing-INCTI-CAIINNO-2015.pdf',
        tags: ['Skills', 'Innovation']
      }
    }
  },
  {
    id: '22',
    slug: 'panorama-de-la-propiedad-intelectual-en-mexico-otra-perspectiva',
    date: '2016',
    languages: {
      es: {
        title: 'Panorama de la propiedad intelectual en México: otra perspectiva',
        description: '',
        image: '/caiinno-publications/22/portada-es.png',
        downloadLink: '/caiinno-publications/22/Estado-general-de-la-propiedad-intelectual-en-M%C3%A9xico.pdf',
        tags: ['Habilidades', 'Innovación']
      },
    }
  },
  {
    id: '23',
    slug: 'emprendimiento-y-genero-en-mexico',
    date: '2017',
    languages: {
      es: {
        title: 'Emprendimiento y género en México',
        description: '',
        image: '/caiinno-publications/23/portada-es.png',
        downloadLink: '/caiinno-publications/23/emprendimiento-y-g%C3%A9nero.pdf',
        tags: ['Habilidades', 'Innovación']
      },
    }
  },
  {
    id: '24',
    slug: 'patentes-verdes-en-el-pais',
    date: '2025',
    languages: {
      es: {
        title: 'Patentes verdes en el país',
        description: '',
        image: '/caiinno-publications/24/portada-es.png',
        downloadLink: '/caiinno-publications/24/patentesverdesenelpais.pdf',
        tags: ['Patentes', 'Innovación', 'Sustentabilidad', 'Medio Ambiente']
      },
    }
  },
  {
    id: '25',
    slug: 'mujeres-inventoras-patentando-en-mexico',
    date: '2015',
    languages: {
      es: {
        title: 'Mujeres inventoras: Patentando en México ¿Cómo vamos?',
        description: '',
        image: '/caiinno-publications/25/portada-es.png',
        downloadLink: '/caiinno-publications/25/Mujeres-Inventoras.pdf',
        tags: ['Patentes', 'Innovación', 'Mujeres', 'Inventoras']
      },
      en: {
        title: 'Women Inventors: Patenting in Mexico How are we doing?',
        description: '',
        image: '/caiinno-publications/25/portada-en.png',
        downloadLink: '/caiinno-publications/25/Women-inventors.pdf',
        tags: ['Innovation', 'Women', 'Patents', 'Inventors']
      }
    }
  },
  {
    id: '26',
    slug: 'formacion-civica-y-etica-en-mexico',
    date: '2017',
    languages: {
      es: {
        title: 'Formación cívica y ética en México',
        description: '',
        image: '/caiinno-publications/26/portada-es.png',
        downloadLink: '/caiinno-publications/26/formacion-civica1.pdf',
        tags: ['Formación Cívica', 'Ética', 'Educación', 'Innovación']
      },
    }
  },
  {
    id: '27',
    slug: 'observatorio-electoral-ciencia-tecnologia-2014-2015',
    date: '2015',
    languages: {
      es: {
        title: 'Observatorio Electoral de Ciencia y Tecnología Ramo 38 (2014-2015)',
        description: '',
        image: '/caiinno-publications/27/portada-es.png',
        downloadLink: '/caiinno-publications/27/Publicaci%C3%B3n-ramo38.pdf',
        tags: ['Observatorio Electoral', 'Ciencia', 'Tecnología', 'Ramo 38']
      }
    }
  },
  {
    id: '28',
    slug: 'observatorio-electoral-ciencia-tecnologia-2016-2017',
    date: '2017',
    languages: {
      es: {
        title: 'Observatorio Electoral de Ciencia y Tecnología Ramo 38 (2016-2017)',
        description: '',
        image: '/caiinno-publications/28/portada-es.png',
        downloadLink: '/caiinno-publications/28/RAMO-38-2016-2017.pdf',
        tags: ['Observatorio Electoral', 'Ciencia', 'Tecnología', 'Ramo 38']
      }
    }
  },
  {
    id: '29',
    slug: 'mujeres-obtentoras',
    date: '2025',
    languages: {
      es: {
        title: 'Mujeres Obtentoras en México del 2019 al 2023',
        description: '',
        image: '/caiinno-publications/29/portada-es.png',
        downloadLink: '/caiinno-publications/29/MUJERES OBTENTORAS EN MEXICO DEL 2019 AL 2023-SEMBRANDO EL FUTURO.pdf',
        tags: ['Observatorio Electoral', 'Ciencia', 'Tecnología', 'Ramo 38']
      },
      en: {
        title: 'Women Plant Breeders in Mexico from 2019 to 2023',
        description: '',
        image: '/caiinno-publications/29/portada-en.png',
        downloadLink: '/caiinno-publications/29/WOMEN PLANT BREEDERS IN MEXICO FROM 2019 TO 2023-SOWING THE FUTURE.pdf',
        tags: ['Electoral Observatory', 'Science', 'Technology', 'Branch 38']
      }
    }
  }
] as const;
